crm/urls.py
from django.urls import path
from .views import ClientCreateView, ClientUpdateView, ClientDeleteView, ClientWalletUpdateView, ClientAPIView, Homepage

app_name = 'crm'

urlpatterns = [
    path("", Homepage.as_view(), name='homepage'),
    path("client-create/", ClientCreateView.as_view(), name="createclient"),
    path("client-update/<int:pk>/", ClientUpdateView.as_view(template_name="crm/updateclient.html"), name="updateclient"),
    path("client-delete/<int:pk>/", ClientDeleteView.as_view(), name='deleteclient'),
    path("edit-balance/<int:pk>/", ClientWalletUpdateView.as_view(), name='updateclientbalance'),
    path('api/getbalance/', ClientAPIView.as_view(), name='api-view'),
]

devtest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm.urls', namespace='crm')),
]

crm/models.py
from django.db import models


class BaseModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Client(BaseModel):
    cid = models.CharField(max_length=60, unique=True, db_index=True)
    first_name = models.CharField(max_length=300)
    last_name = models.CharField(
        max_length=300, null=True, blank=True, default="")
    country_code = models.CharField(
        max_length=30, blank=True, null=True, default="")
    email = models.EmailField()
    address = models.TextField()
    phone = models.CharField(max_length=50, null=True, blank=True, default="")

    class Meta:
        ordering = ['cid']

    def __str__(self):
        return self.cid

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"


class ClientWallet(BaseModel):
    clients = models.OneToOneField(Client, on_delete=models.CASCADE)
    total_balance = models.DecimalField(
        max_digits=20, decimal_places=2, default=0)
    available_balance = models.DecimalField(
        max_digits=20, decimal_places=2, default=0)
    lien_balance = models.DecimalField(
        max_digits=20, decimal_places=2, default=0)

    def __str__(self):
        return f"{self.cid} - {self.available_balance}"

    @property
    def cid(self):
        return self.clients.cid

crm/views.py
from django.shortcuts import render
from .models import Client, ClientWallet
from rest_framework.views import APIView
from .serializers import ClientSerializer
from django.views.generic import CreateView, UpdateView, DeleteView
from rest_framework import status
from rest_framework.response import Response
from django.views import View

# Create your views here.
class Homepage(View):
    def get(self, request, *args, **kwargs):
        qs = Client.objects.all()
        return render(request, 'home.html', {'qs': qs})

class ClientCreateView(CreateView):
    model = Client
    fields = ['cid', 'first_name', 'last_name', 'country_code', 'email', 'address', 'phone']
    success_url = '/'

class ClientUpdateView(UpdateView):
    model = Client
    fields = ['cid', 'first_name', 'last_name', 'country_code', 'email', 'address', 'phone']
    success_url = '/'

class ClientDeleteView(DeleteView):
    model = Client
    success_url = '/'

class ClientWalletUpdateView(UpdateView):
    model = ClientWallet
    fields = ['clients', 'available_balance']
    success_url = '/'

class ClientAPIView(APIView):
    def post(self, request):
        data = request.data
        serializer = ClientSerializer(data = data)

        if serializer.is_valid():
            cid = serializer.data['cid']            
            try:
                acct = Client.objects.get(cid = cid)
                acct_bal = acct.clientwallet.available_balance
                acct_name = acct.first_name
                details = {'Name': acct_name, 'Balance': acct_bal}
                return Response({'details': details}, status=status.HTTP_200_OK)
            except: 
                return Response({'message': 'This CID does not have an account'}, status=status.HTTP_400_BAD_REQUEST)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">

    <title>Afex Task</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light py-3">
        <div class="container">
          <a class="navbar-brand" href="#">Afex</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  </body>

</html>

templates/crm/client_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <section class = "mb-4">
      <div class="container py-3">
        <form method="POST">
          {% csrf_token %}
          <h2 class="text-center"> Create a Client</h2>
          {{ form|crispy }}
          <center><button type="submit" class="btn btn-primary mt-4 shadow">Create Client</button></center>
        </form>
      </div>
    </section>
{% endblock content %}

templates/crm/clientwallet_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <section class = "mb-4">
      <div class="container py-3">
        <form method="POST">
          {% csrf_token %}
          <h2 class="text-center"> Client Wallet</h2>
          {{ form|crispy }}
          <center><button type="submit" class="btn btn-primary mt-4 shadow">Update Client</button></center>
        </form>
      </div>
    </section>
{% endblock content %}

templates/crm/updateclient.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <section class = "mb-4">
      <div class="container py-3">
        <form method="POST">
          {% csrf_token %}
          <h2 class="text-center"> Update a Client</h2>
          {{ form|crispy }}
          <center><button type="submit" class="btn btn-primary mt-4 shadow">Update Client</button></center>
        </form>
      </div>
    </section>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
<section class="mb-4">
  <div class="container mt-4">
    <div class="row">
      <div class="card py-3 shadow">
        <h2 class="text-center">Clients</h2>
        <table class="table table-responsive">
            <thead>
              <tr>
                <th scope="col">ID</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
                <th scope="col">Address</th>
                <th scope="col"></th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              {% for i in qs %}
              <tr>
                <td>{{i.cid}}</td>
                <td>{{i.first_name}}</td>
                <td>{{i.last_name}}</td>
                <td>{{i.email}}</td>
                <td>{{i.phone}}</td>
                <td>{{i.address}}</td>
                <td><a href="{% url 'crm:updateclient' i.id %}" class="btn btn-secondary">UPDATE</a></td>
                <td><a href="{% url 'crm:deleteclient' i.id %}" class="btn btn-danger">DELETE</a></td>
              </tr>
              {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'crm:createclient' %}" class="btn btn-primary">CREATE CLIENT</a>
      </div>
    </div>
  </div>
</section>

<section class="mt-3">
    <div class="container">
      <div class="row">
        <div class="card shadow">
          <h2 class="text-center mt-3">Fund Wallet</h2>
          <table class="table table-responsive">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Available Balance</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for j in qs %}
                  <tr>
                    <td>{{j.cid}}</td>
                    <td>{{j.first_name}}</td>
                    <td>{{j.last_name}}</td>
                    <td>{{j.clientwallet.available_balance}}</td>
                    <td><a href="{% url 'crm:updateclientbalance' j.clientwallet.id %}" class="btn btn-secondary">UPDATE</a></td>
                  </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
</section>

<section class="mt-3 mb-3">
    <div class="container">
      <div class="row">
        <div class="card shadow">
          <h2 class="text-center mt-3">Web Socket</h2>
          <form id="form" action=".">
            <h2>Update Client Wallet</h2>

            <div class="form-group mb-2 p-3">
                <label>CID</label><br />
                <input type="number" name="cid" />
            </div>
            <div class="form-group mb-2 p-3">
                <label>Total Balance</label><br />
                <input type="number" name="total_balance" />
            </div>
            <div class="form-group mb-2 p-3">
                <label>Available Balance</label><br />
                <input type="number" name="available_balance" />
            </div>

            <input type="submit" name="submit" class="mb-2 p-3 btn btn-primary"/>
          </form>

          <div id="message"></div>

        </div>
      </div>
    </div>
</section>

<script type="text/javascript">
    let url = `ws://${window.location.host}/ws/socket-server/`

    const afexSocket = new WebSocket(url)

    afexSocket.onmessage = function(e){
        let data = JSON.parse(e.data)
        console.log('Data:', data)

        if(data.type === 'chat'){
            let messages = document.getElementById('message')
            messages.insertAdjacentHTML('beforeend', `<div>
                            <p>${data.cid} account balance is ${data.available_balance}</p>
                        </div>`)
        }
    }

    let form = document.getElementById('form')
    form.addEventListener('submit', (e)=> {
        e.preventDefault()
        let cid = e.target.cid.value
        let total_balance = e.target.total_balance.value
        let available_balance = e.target.available_balance.value
        afexSocket.send(JSON.stringify({
            'cid': cid,
            'total_balance': total_balance,
            'available_balance': available_balance
        }))
        form.reset()
    })
</script>
{% endblock content %}